### PR TITLE
Made some minor changes to the return values

### PR DESCRIPTION
**Pull request by vyshnav-vinod**
Hey, its me from reddit. Saw some minor changes that can be made and decided to open a PR. Also this is a sqlite viewer right? or a sqlite wrapper for Go? And by viewer you mean some GUI or TUI? Sorry i really couldnt understand where this was going :)

### CODE REVIEW

**Comment by soerenlemke** [comment]
Hi there, thank you! This should be a sqlite viewer. But I`m not quite sure if it`s better to be GUI or TUI. Would be great to have like a Web GUI. What do you think? Maybe with htmx? I haven`t done real web projects with Go so far so I`m not sure.

**Comment by vyshnav-vinod** [comment]
I also have thought about Web GUI. But same as you i havent worked with web in go (i have some experience in python). It would be fun to setup a web GUI

**Comment by soerenlemke** [comment]
Sounds good!

**Comment by vyshnav-vinod** [comment]
Do you want to connect or discord? or reddit?

**Comment by soerenlemke** [comment]
Do you think we can communicate with issues and here? Otherwise we can type on Discord or Reddit :)

**Comment by vyshnav-vinod** [comment]
I am fine with anything. :)

**Comment by soerenlemke** [comment]
So lets try the communication here :) If we find some more contributors we can maybe setup a disc. But i like to practice communication directly in the project because thats were I have to approve.

**Comment by vyshnav-vinod** [comment]
Ok :)

**Comment by soerenlemke** [comment]
If you want you can make your thoughts about the Web GUI and setting it up with "fake data".

**Pull request merged**
